services:
  db:
    image: postgres
    container_name: 421_final
    restart: always
    environment:
      POSTGRES_USER: comp421
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
